[display]
compact = false
use_pager = true
show_title = false

[style.command_name]
foreground = "red"

[style.example_text]
foreground = "magenta"

[style.example_code]
foreground = "cyan"

[style.example_variable]
foreground = "cyan"
underline = true

[updates]
auto_update = true
download_languages = ["zh", "en"]

[search]
languages = ["zh", "en"]


