# Navi configuration file

style:
  tag:
    color: cyan
  comment:
    color: blue
  snippet:
    color: white

cheats:
  # This points to your custom cheats directory in dotfiles
  paths:
    - ~/dotfiles/cheats